---
name: build

"on":
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      ros_version:
        description: RouterOS Version
        required: true

env:
  TEST_TAG: routerostest
  DEFAULT_VERSION: "6.48.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: ROUTEROS_VERSION=${{ inputs.ros_version || env.DEFAULT_VERSION }}

      - name: Test
        run: |
          docker run -d --rm --cap-add=NET_ADMIN -v /dev/net/tun:/dev/net/tun -p 2222:22 ${{ env.TEST_TAG }}

          for i in {1..20}; do ssh-keyscan -p 2222 localhost && break || echo -e "\033[0;33mNot started yet ($i)\033[0m" && sleep 10; done
          ssh-keyscan -p 2222 localhost

          sshpass -p "" ssh -p 2222 -o StrictHostKeyChecking=no -T admin@localhost << EOF
          /system resource print
          EOF

      - name: Build and push
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:${{ inputs.ros_version || env.DEFAULT_VERSION }}
          push: true
          build-args: ROUTEROS_VERSION=${{ inputs.ros_version || env.DEFAULT_VERSION }}
